name: Issue Report
description: Report a bug or any issue
body:
  - type: textarea
    id: what-happened
    attributes:
      label: Describe the bug
      placeholder: A clear and concise description of what the bug is.
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: To Reproduce
      description: Steps to reproduce the behavior:
      placeholder: "1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error"
    validations:
      required: true
  - type: input
    id: mversion
    attributes:
      label: Minecraft version
      description: What version of Minecraft are you using?
    validations:
      required: true
  - type: dropdown
    id: lversion
    attributes:
      label: Loader
      description: Which loader are you using?
      options:
        - Paper
        - Forge
        - Fabric
        - NeoForge
    validations:
      required: true
  - type: input
    id: logs
    attributes:
      label: Logs
      description: Please upload your log file from logs/latest.log to https://gist.github.com/ and put in the link below. It always contains needed, important information.
      placeholder: ex. https://gist.github.com/someaddons/aa5986b9495863c3b5
    validations:
      required: true
